services:
  product-db:
    image: postgres:17
    container_name: product-db
    env_file: ".env"
    restart: unless-stopped
    ports:
      - "${PRODUCT_DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 3
    expose:
      - "5432"
      - "3000"
    volumes:
      - product-db-volume:/var/lib/postgresql/data
    networks:
      - project-network

  payment-db:
    image: postgres:17
    container_name: payment-db
    env_file: ".env"
    restart: unless-stopped
    ports:
      - "${PAYMENT_DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 3
    expose:
      - "5432"
      - "3001"
    volumes:
      - payment-db-volume:/var/lib/postgresql/data
    networks:
      - project-network

  user-db:
    image: postgres:17
    container_name: user-db
    env_file: ".env"
    restart: unless-stopped
    ports:
      - "${USER_DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 3
    expose:
      - "5432"
      - "3002"
    volumes:
      - user-db-volume:/var/lib/postgresql/data
    networks:
      - project-network

  order-db:
    image: mongo:8
    container_name: order-db
    env_file: ".env"
    restart: unless-stopped
    expose:
      - "5432"
      - "3003"
    ports:
      - "${ORDER_DB_PORT}:27017"
    volumes:
      - order-db-volume:/data/db
    networks:
      - project-network

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: notification-service
    env_file: ".env"
    ports:
      - "${NOTIFICATION_SERVICE_PORT}:8000"
    healthcheck:
      test: [ "CMD", "curl", "http://0.0.0.0:${NOTIFICATION_SERVICE_PORT}/" ]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - project-network

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    depends_on:
      - order-db
    restart: unless-stopped
    container_name: order-service
    env_file: ".env"
    ports:
      - "${ORDER_SERVICE_PORT}:8000"
    healthcheck:
      test: [ "CMD", "curl", "http://0.0.0.0:${ORDER_SERVICE_PORT}/" ]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - project-network

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    depends_on:
      payment-db:
        condition: service_healthy
    restart: unless-stopped
    container_name: payment-service
    env_file: ".env"
    ports:
      - "${PAYMENT_SERVICE_PORT}:8000"
    healthcheck:
      test: [ "CMD", "curl", "http://0.0.0.0:${PAYMENT_SERVICE_PORT}/" ]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - project-network

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    depends_on:
      product-db:
        condition: service_healthy
    restart: unless-stopped
    container_name: product-service
    env_file: ".env"
    ports:
      - "${PRODUCT_SERVICE_PORT}:8000"
    healthcheck:
      test: [ "CMD", "curl", "http://0.0.0.0:${PRODUCT_SERVICE_PORT}/" ]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - project-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    depends_on:
      user-db:
        condition: service_healthy
    restart: unless-stopped
    container_name: user-service
    env_file: ".env"
    ports:
      - "${USER_SERVICE_PORT}:8000"
    healthcheck:
      test: [ "CMD", "curl", "http://0.0.0.0:${USER_SERVICE_PORT}/" ]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - project-network

volumes:
  product-db-volume:
  payment-db-volume:
  user-db-volume:
  order-db-volume:
    driver: local

networks:
  project-network:
    driver: bridge
