services:
  # notification-service:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   container_name: notification-service
  #   env_file: ".env"
  #   ports:
  #     - "${NOTIFICATION_SERVICE_PORT}:8000"
  #   healthcheck:
  #     test: [ "CMD", "curl", "http://0.0.0.0:${NOTIFICATION_SERVICE_PORT}/" ]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 3
  #   networks:
  #     - notification-service-network

  # order-service:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   container_name: order-service
  #   env_file: ".env"
  #   ports:
  #     - "${ORDER_SERVICE_PORT}:8000"
  #   healthcheck:
  #     test: [ "CMD", "curl", "http://0.0.0.0:${ORDER_SERVICE_PORT}/" ]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 3
  #   networks:
  #     - order-service-network

  # payment-service:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   container_name: payment-service
  #   env_file: ".env"
  #   ports:
  #     - "${PAYMENT_SERVICE_PORT}:8000"
  #   healthcheck:
  #     test: [ "CMD", "curl", "http://0.0.0.0:${PAYMENT_SERVICE_PORT}/" ]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 3
  #   networks:
  #     - payment-service-network

  # product-service:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   container_name: product-service
  #   env_file: ".env"
  #   ports:
  #     - "${PRODUCT_SERVICE_PORT}:8000"
  #   healthcheck:
  #     test: [ "CMD", "curl", "http://0.0.0.0:${PRODUCT_SERVICE_PORT}/" ]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 3
  #   networks:
  #     - product-service-network

  # user-service:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   container_name: user-service
  #   env_file: ".env"
  #   ports:
  #     - "${USER_SERVICE_PORT}:8000"
  #   healthcheck:
  #     test: [ "CMD", "curl", "http://0.0.0.0:${USER_SERVICE_PORT}/" ]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 3
  #   networks:
  #     - user-service-network

  order-db:
    image: postgres:17
    container_name: order-db
    env_file: ".env"
    restart: always
    ports:
      - "${ORDER_DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - order-db-volume:/var/lib/postgresql/data
    networks:
      - order-db-network

  payment-db:
    image: postgres:17
    container_name: payment-db
    env_file: ".env"
    restart: always
    ports:
      - "${PAYMENT_DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - payment-db-volume:/var/lib/postgresql/data
    networks:
      - payment-db-network

  user-db:
    image: postgres:17
    container_name: user-db
    env_file: ".env"
    restart: always
    ports:
      - "${USER_DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - user-db-volume:/var/lib/postgresql/data
    networks:
      - user-db-network

volumes:
  order-db-volume:
  payment-db-volume:
  user-db-volume:
    driver: local

networks:
  notification-service-network:
  order-service-network:
  payment-service-network:
  product-service-network:
  user-service-network:
  order-db-network:
  payment-db-network:
  user-db-network:
    driver: bridge
