services:
  product-db:
    image: postgres:17
    container_name: product-db
    env_file: ".env"
    restart: unless-stopped
    ports:
      - "${PRODUCT_DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 3
    expose:
      - "5432"
      - "3000"
    volumes:
      - product-db-volume:/var/lib/postgresql/data
    networks:
      - project-network

  payment-db:
    image: postgres:17
    container_name: payment-db
    env_file: ".env"
    restart: unless-stopped
    ports:
      - "${PAYMENT_DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 3
    expose:
      - "5432"
      - "3001"
    volumes:
      - payment-db-volume:/var/lib/postgresql/data
    networks:
      - project-network

  user-db:
    image: postgres:17
    container_name: user-db
    env_file: ".env"
    restart: unless-stopped
    ports:
      - "${USER_DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 3
    expose:
      - "5432"
      - "3002"
    volumes:
      - user-db-volume:/var/lib/postgresql/data
    networks:
      - project-network

  order-db:
    image: mongo:8
    container_name: order-db
    env_file: ".env"
    restart: unless-stopped
    expose:
      - "5432"
      - "3003"
    ports:
      - "${ORDER_DB_PORT}:27017"
    volumes:
      - order-db-volume:/data/db
    networks:
      - project-network

volumes:
  product-db-volume:
  payment-db-volume:
  user-db-volume:
  order-db-volume:
    driver: local

networks:
  project-network:
    driver: bridge
